### ISSUE TITLE
Fonts are not checking the `Target Membership` box in Xcode project on Target Membership menu

### ISSUE THREAD

**Issue by jottenlips** [gitn00b1337/expo-native-fonts#2]
```
      [
        "@bittingz/expo-native-fonts",
        {
          srcFolder: "./widgets/fonts",
          fonts: [
            {
              filePath: "Roboto/RobotoMono-RegularEmojis.ttf",
              targets: ["vestaboardWidgetExtension"],
              platform: "ios",
            },
            {
              filePath: "Roboto/Roboto-RegularEmojis.ttf",
              targets: ["vestaboardWidgetExtension"],
              platform: "ios",
            },
          ],
        },
      ],
    ```
    
    Manually checking the box seems to work.

**Comment by jottenlips** [comment]
<img width="1398" alt="Screenshot 2024-05-08 at 4 35 17 PM" src="https://github.com/gitn00b1337/expo-native-fonts/assets/14910912/3753602a-900f-4774-ad10-4ec226adae98"> full screenshot

**Comment by mike-stewart-dev** [comment]
Ok I'll take a look asap. How urgent is this? Thanks

**Comment by mike-stewart-dev** [comment]
The config is adding correctly but it seems to get deleted by expo during the pod install step. I'm still looking into this but it might be an expo issue.

**Comment by mike-stewart-dev** [comment]
Hi, v0.1.15 is now released and should fix this.

**Comment by jottenlips** [comment]
Thank you! 🙏 works for me!
